### ISSUE TITLE
Actually useful for preventing fingerprinting?

### ISSUE THREAD

**Issue by cmawhorter** [dadrian/clienthello-randomization#2]
Not sure how I ended up down this rabbit hole, but came by way of the webkit standards positions repo --

It seems like randomization isn't enough to prevent fingerprinting. For example, [JA3 works around randomization](https://github.com/salesforce/ja3#how-it-works) and references [GREASE](https://datatracker.ietf.org/doc/html/draft-davidben-tls-grease-01).

So if, (AFAICT) one of the leading methods for fingerprinting, shrugs off randomization... is it useful?

**Comment by dadrian** [comment]
The goal isn't to stop all fingerprinting, it's to ensure that the ecosystem:
1. Is prepared for the structure of the ClientHello to change over time
2. Does not hardcode byte-offsets / assume specific orderings of fields

This means that future changes to TLS will be easier to deploy.

**Comment by cmawhorter** [comment]
That was mostly my takeaway from the explainer but with the mention of fingerprinting, I figured I'd throw it out there.
